// generators/app/templates/front-end/react/src/components/home/home.js
import React    from 'react'

import { Link } from 'react-router-dom'

import Page     from '../Page'

const Home = () =>
    <Page header="Home">
        <p>
            ReactJS Single Page Application.
        </p>
        <span><Link className="App-link" to="/users">Users</Link> | <Link className="App-link" to="/no/such/route">No Such Route</Link></span>
    </Page>

export default Home

// generators/app/templates/front-end/vue/src/views/home/Home.vue
<template>
  <div>
    <h1>Home</h1>
    <p>
        VueJS Single Page Application.
    </p>
    <span><router-link class="App-link" to="/users">Users</router-link> | <router-link class="App-link" to="/no/such/route">No Such Route</router-link></span>
  </div>
</template>

<script>
// @ is an alias to /src
//import HelloWorld from '@/components/HelloWorld.vue'

export default {
  name: 'home',
  components: {
  }
}
</script>

<style>
</style>
